title: Software and Data for Supporting Network Science
description: "A NetSci 2025 Satellite Workshop<br><span style='font-size: 80%'>18 June 2024, Maastricht, Netherlands</span>"

timezone: Europe/Amsterdam

navigation:
  Home: "/"
  Schedule: "/schedule"
  Call for Abstracts: "/cfa"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

include: ['abstracts']

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
